export const PUBLIC_CARD_QUERY = `
  query PublicCard($id: String!, $source: String) {
    publicCard(id: $id, source: $source) {
      id
      userId
      firstName
      lastName
      jobTitle
      profilePhoto
      companyName
      companyEmail
      companyPhone
      companyWebsite
      companyAddress
      companyLogo
      about
      industry
      specialties
      location
      companySize
      templateId
      themeId
      name
      isPrivate
      middleName
      prefix
      suffix
      preferredName
      pronouns
      maidenName
      bio
      department
      headline
      skills
      personalWebsite
      discord
      wechat
      line
      signal
      linkedin
      instagram
      x
      facebook
      tiktok
      youtube
      github
      dribbble
      behance
      snapchat
      pinterest
      whatsapp
      telegram
      threads
      patreon
      spotify
      soundcloud
      appleMusic
      teams
      meet
      zoom
      webex
      calendly
      bookings
      videoLink
      fileUpload
      displaySettings
      customStyles
      frontImageUrl
      backImageUrl
      createdAt
      updatedAt
      theme {
        id
        name
        displayName
        description
        isDefault
        isPremium
        frontPreviewUrl
        author
        version
        frontHtml
        backHtml
        styleSchema
        defaultDisplaySettings
        isActive
        backPreviewUrl
        createdAt
        updatedAt
      }
    }
  }
`;
